[package]
name = "pin-gen"
authors = ["zSchoen <dev@zschoen.dev>"]
license = "GPL-3.0-only"
readme = "README.md"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pin-data = { path = "../pin-data" }
thiserror.workspace = true
error-stack.workspace = true
sysexits = "0.10"
argon2.workspace = true
rand_core = { version = "0.9", features = ["std"] }
rpassword = "7.4"
secstr.workspace = true
clap = { version = "3.2", features = ["derive", "env"] }
birdcage = { workspace = true, optional = true }

[features]
default = ["sandbox"]
sandbox = ["dep:birdcage"]

[lints]
workspace = true
